### ISSUE TITLE
Instalation via Luarocks on OSX fails

### ISSUE THREAD

**Issue by renatosc** [mikejsavage/lua-bcrypt#10]
I am trying to install lua-bcrypt using luarocks, but the building process is failing:
`installing https://luarocks.org/bcrypt-2.1-3.src.rock...
Using https://luarocks.org/bcrypt-2.1-3.src.rock... switching to 'build' mode
Warning: variable CFLAGS was not passed in build_variables
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -I/usr/local/include -DOPENSSL_cleanse=explicit_bzero -D__BSD_VISIBLE -DHAVE_STRNDUP -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG -O0 -c -o compat/safebfuns.o compat/safebfuns.c
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -I/usr/local/include -DOPENSSL_cleanse=explicit_bzero -D__BSD_VISIBLE -DHAVE_STRNDUP -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/bcrypt/bcrypt.o compat/bcrypt/bcrypt.c
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -I/usr/local/include -DOPENSSL_cleanse=explicit_bzero -D__BSD_VISIBLE -DHAVE_STRNDUP -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/bcrypt/blowfish.o compat/bcrypt/blowfish.c
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -I/usr/local/include -DOPENSSL_cleanse=explicit_bzero -D__BSD_VISIBLE -DHAVE_STRNDUP -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/arc4random/arc4random.o compat/arc4random/arc4random.c
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -I/usr/local/include -DOPENSSL_cleanse=explicit_bzero -D__BSD_VISIBLE -DHAVE_STRNDUP -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/strlcpy.o compat/strlcpy.c
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -I/usr/local/include -DOPENSSL_cleanse=explicit_bzero -D__BSD_VISIBLE -DHAVE_STRNDUP -Iinclude -Wall -Wno-pointer-sign -O2 -fPIC -DNDEBUG   -c -o compat/sha/sha512.o compat/sha/sha512.c
compat/sha/sha512.c:13:10: fatal error: 'openssl/opensslconf.h' file not found`

I have openssl (installed via homebrew) but it is not located under /usr/local/  (it is instead at /usr/local/opt/).  From what I understand, you are not exposing the OPENSSL_DIR in your rockspec file, so I cannot do something like:
`luarocks install bcrypt OPENSSL_DIR=/usr/local/opt/`
as other luarocks module allow (luasec module is an example that allows us to do that).

**Comment by mikejsavage** [comment]
Hi sorry this is super late, but the OSX version should not have needed OpenSSL at all.

I've pushed a fix to remove the OpenSSL dependency, which should clean this up too.

**Comment by karlseguin** [comment]
mind pushing that to luarocks?

**Comment by mikejsavage** [comment]
Done, let me know if it doesn't work for you
