### ISSUE TITLE
Not compiling with musl c library

### ISSUE THREAD

**Issue by cdrubin** [mikejsavage/lua-bcrypt#11]
Ahoy! Thanks for a useful library!

musl based builds break here:

```
include/pwd.h:93:14: error: expected ';' before 'struct'
 __BEGIN_DECLS
              ^
              ;
 struct passwd *getpwuid(uid_t);
 ~~~~~~        
```

because of __BEGIN_DECLS  

According to the musl c library FAQ this is an issue with lua-bcrypt in this case. Would you be willing to to make the substitutions mentioned here:

https://wiki.musl-libc.org/faq.html

which is to : 

replace all occurrences of:

```
__BEGIN_DECLS
```
with

```
#ifdef __cplusplus
extern "C" {
#endif
```
and all occurrences of

```
__END_DECLS
```
with
```
#ifdef __cplusplus
}
#endif
```

Thanks!

**Comment by mikejsavage** [comment]
Now I look at it again there's a lot of cruft in the OpenBSD stuff :)

In this case those lines can just be deleted since the project is compiled as C.

Thanks for the report!

**Comment by vadi2** [comment]
Would you mind publishing an updated rock with this? As it stands the library can't be installed in Docker Alpine images.

**Comment by mikejsavage** [comment]
Done, please let me know if it works

**Comment by vadi2** [comment]
I can confirm that it works, thanks for the quick turnaround! Going to be using this in combination with Lapis for Mudlet's [package manager](https://github.com/Mudlet/mudlet-package-repo) site.
