### ISSUE TITLE
Not working on Linux kernel less than 3.17

### ISSUE THREAD

**Issue by catbro666** [mikejsavage/lua-bcrypt#21]
Before linux kernel 3.17, the syscall `getrandom` is not supported. 
I noticed that before v2.1, if `getrandom` is not supported, it will fallback to use `/dev/urandom`, but it's removed from v2.2.
I wonder why this fallback mechanism was removed.

**Comment by mikejsavage** [comment]
Hi,

https://en.wikipedia.org/wiki/Linux_kernel_version_history

3.17 was EOL'd almost 8 years ago. I'm surprised to see that 3.16 was supported up until a bit over 2 years ago.

I have no plans to readd support for EOL kernel versions
