### ISSUE TITLE
Installation fails on OS X with clang-aliased gcc

### ISSUE THREAD

**Issue by enquora** [mikejsavage/lua-bcrypt#6]
Error from luarocks install bcrypt on OS X:

Installing https://rocks.moonscript.org/bcrypt-1.5-1.src.rock...
Using https://rocks.moonscript.org/bcrypt-1.5-1.src.rock... switching to 'build' mode
Warning: variable CFLAGS was not passed in build_variables
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -O2 -shared -fPIC -std=c99 -D_GNU_SOURCE -Wall -Wextra -Wno-nonnull -Wwrite-strings -Wformat=2 -DNDEBUG -Ilib/bcrypt -I/usr/local/opt/lua/include   -c -o src/main.o src/main.c
clang: warning: argument unused during compilation: '-shared'
make -C lib/bcrypt
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -c -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wundef -Wpointer-arith -O2 -fomit-frame-pointer -funroll-loops -fPIC crypt_blowfish.c
crypt_blowfish.c:898:24: warning: cast from 'const char *' to 'const BF_word *' (aka 'const unsigned int *') increases
      required alignment from 1 to 4 [-Wcast-align]
        BF_encode(&output[7], (const BF_word *)input, 16);
                              ^~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -c x86.S
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -c -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wundef -Wpointer-arith -O2 -fomit-frame-pointer -funroll-loops -fPIC crypt_gensalt.c
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -c -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wundef -Wpointer-arith -O2 -fomit-frame-pointer -funroll-loops -fPIC wrapper.c
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -o bcrypt.so src/main.o lib/bcrypt/crypt_blowfish.o lib/bcrypt/x86.o lib/bcrypt/crypt_gensalt.o lib/bcrypt/wrapper.o -O2 -shared -fPIC -std=c99 -D_GNU_SOURCE -Wall -Wextra -Wno-nonnull -Wwrite-strings -Wformat=2 -DNDEBUG -Ilib/bcrypt -I/usr/local/opt/lua/include
Undefined symbols for architecture x86_64:
  "_luaL_checkinteger", referenced from:
      _luabcrypt_salt in main.o
  "_luaL_checklstring", referenced from:
      _luabcrypt_digest in main.o
      _luabcrypt_verify in main.o
      _luabcrypt_random in main.o
  "_luaL_setfuncs", referenced from:
      _luaopen_bcrypt in main.o
  "_lua_createtable", referenced from:
      _luaopen_bcrypt in main.o
  "_lua_error", referenced from:
      _luaopen_bcrypt in main.o
      _luabcrypt_digest in main.o
      _luabcrypt_salt in main.o
      _luabcrypt_random in main.o
  "_lua_pushboolean", referenced from:
      _luabcrypt_verify in main.o
  "_lua_pushstring", referenced from:
      _luaopen_bcrypt in main.o
      _luabcrypt_digest in main.o
      _luabcrypt_salt in main.o
      _luabcrypt_random in main.o
  "_lua_tointegerx", referenced from:
      _luabcrypt_digest in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bcrypt.so] Error 1

Error: Build error: Failed building.

Removing '-static' from Makefile and adding '-bundle -undefined dynamic_lookup'  fixes problem.

**Comment by zach-binary** [comment]
Works much better now, no warnings.  Tried everything and the library appears to be working fine on my Mac.  Thank you :)

**Comment by mikejsavage** [comment]
Finally.

Thanks for all the feedback. Closing!
