### ISSUE TITLE
Not running on Raspbian due to missing LDFLAG

### ISSUE THREAD

**Issue by M4he** [mikejsavage/lua-bcrypt#7]
Installing bcrypt on Raspbian via `# luarocks install bcrypt` will result in the following error when trying to use it in a lua script:
```
lua: error loading module 'bcrypt' from file '/usr/local/lib/lua/5.1/bcrypt.so':
        /usr/local/lib/lua/5.1/bcrypt.so: undefined symbol: clock_gettime
```
Apparently, Raspbian uses an old glibc version (2.13). Versions older than 2.17 will need an additional `-lrt` linker flag for this to work, as far as I can tell from googling this issue.

I downloaded and unpacked the rock and put a `LDFLAGS += -lrt` into the **Makefile.mess** file. After building and installing it through luarocks it seems to run fine on my Raspberry now.

**Comment by mikejsavage** [comment]
[2.17 is over two years old](http://www.gnu.org/software/libc/) and there have been [18 CVE's since then](http://www.cvedetails.com/vulnerability-list/vendor_id-72/product_id-767/GNU-Glibc.html). This is a bug in Raspian.

**Comment by mikejsavage** [comment]
Sorry for the attitude. This is now fixed.
